### ISSUE TITLE
KafkaEx.GenConsumer has an unhandled `handle_info` case

### ISSUE THREAD

**Issue by craig-day** [kafkaex/kafka_ex#262] opened 2017-12-08 20:20 UTC
Every time a message comes across the topic I'm watching, I see the consumer crash and then restart. This doesn't actually cause any problems thanks to the supervisor, but why does it crash? 

Here are the errors I see

```
[debug] Committed offset maxwell.tickets/0@34 for ticket_consumer
[error] GenServer #PID<0.734.0> terminating
** (FunctionClauseError) no function clause matching in KafkaEx.GenConsumer.handle_info/2
    lib/kafka_ex/gen_consumer.ex:440: KafkaEx.GenConsumer.handle_info({:EXIT, #PID<0.738.0>, :normal}, %KafkaEx.GenConsumer.State{acked_offset: 34, commit_interval: 1000, commit_threshold: 100, committed_offset: 33, consumer_module: KafkaConsumer.Ticket, consumer_state: nil, current_offset: 34, group: "ticket_consumer", last_commit: -576459385603, partition: 0, topic: "maxwell.tickets", worker_name: #PID<0.735.0>})
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:EXIT, #PID<0.738.0>, :normal}
State: %KafkaEx.GenConsumer.State{acked_offset: 34, commit_interval: 1000, commit_threshold: 100, committed_offset: 33, consumer_module: KafkaConsumer.Ticket, consumer_state: nil, current_offset: 34, group: "ticket_consumer", last_commit: -576459385603, partition: 0, topic: "maxwell.tickets", worker_name: #PID<0.735.0>}
[debug] Succesfully connected to broker "172.18.0.12":9092
[debug] Establishing connection to broker 0: "kafka.docker" on port 9092
[debug] Succesfully connected to broker "kafka.docker":9092
```

Any pointers are appreciated

**Comment by dantswain** [comment] 2017-12-08 20:32
Hi @craig-day this looks like some process that your consumer is linked to is crashing and the consumer is catching the `{:EXIT, _, _}` signal. It would be helpful to figure out which process `#PID<0.738.0>` is.

**Comment by craig-day** [comment] 2017-12-09 21:19
Thanks for the response @dantswain. After a little more digging, it was an interesting failure message. It turns out that was because I didn't have the `snappy` dependency, but didn't see a useful log message in my dev environment. In my production environment I got a much more useful error message. 

```
20:19:39.521 [error] GenServer #PID<0.1419.0> terminating
** (UndefinedFunctionError) function :snappy.decompress/1 is undefined (module :snappy is not available)
```

**Comment by dantswain** [comment] 2017-12-09 22:17
Thanks for following up on this, @craig-day !   This is a little tricky for us because not every user requires compression, so we can't really require the compression dependencies.  Since you've found the root cause of your issue, I'm going to close this.  I've opened #263 to keep track of investigating ways to improve the feedback to the user in this kind of situation.

**Closed by dantswain** 2017-12-09 22:17 UTC

**Comment by craig-day** [comment] 2017-12-09 22:22
Awesome. Thanks! Yeah this is an interesting case. I'm mostly interested in why there were two failure modes here. I'll keep an eye on #263 and see if I can contribute anything useful.

**Comment by dantswain** [comment] 2017-12-09 22:24
@craig-day my gut is that you have different logging levels/configs for prod and develop, and that they were the same failure mechanism but you saw them through different lenses.  Are they the same versions of Elixir and OTP?

**Comment by craig-day** [comment] 2017-12-09 22:27
Same versions of elixir and OTP (running in a docker container) but the log level might be different. I'm using this in an umbrella app, and don't change logging in the app where I use kafka_ex, but in my umbrella app config I do set the logger level to info in prod. I can play around with that to see if I can get the error to appear in dev.
