### ISSUE TITLE
Consuming unstable when broker in cluster goes down

### ISSUE THREAD

**Issue by leifg** [kafkaex/kafka_ex#121] opened 2016-06-09 14:17 UTC
I am currently evaluating kafka for internal purposes.

I set up a kafka cluster with 3 nodes (kafka.1, kafka.2 and kafka.3). the topic (name: "topic") I am subscribing to has 3 partitions and is replicated over 3 nodes:

```bash
$ /opt/kafka/bin/kafka-topics.sh --describe --zookeeper $KAFKA_ZOOKEEPER_CONNECT --topic topic
Topic:topic  PartitionCount:3        ReplicationFactor:3     Configs:
        Topic: topic Partition: 0    Leader: 3       Replicas: 3,1,2 Isr: 2,3,1
        Topic: topic Partition: 1    Leader: 1       Replicas: 1,2,3 Isr: 2,3,1
        Topic: topic Partition: 2    Leader: 2       Replicas: 2,3,1 Isr: 2,3,1
```

It's all great I am subscribing to the topic in a very simple way (endless loop, fetch all the time):

```elixir
defp fetch_loop(topic, partition, offset) do
  new_offset = KafkaEx.fetch(topic, partition, offset: offset) |> handle_batch
  persist_offset(new_offset)
  fetch_loop(topic, partition, new_offset)
end
```

This works fine.

But now I also wanted to test what happens if one of the nodes goes down. In theory that should not matter as the cluster will redistribute the leaders.

However my script will crash and display this message:

```elixir
16:02:39.053 [error] Sending data to broker "kafka.3", 9094 failed with :timeout

16:02:39.054 [debug] Shutting down worker KafkaEx.Server

16:02:39.081 [debug] Succesfully connected to "kafka" on port 9092
** (exit) exited in: GenServer.call(KafkaEx.Server, {:fetch, "topic", 2, 63194, 10, 1, 1000000, true}, 5000)
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in KafkaEx.Protocol.Fetch.parse_response/1
            (kafka_ex) lib/kafka_ex/protocol/fetch.ex:18: KafkaEx.Protocol.Fetch.parse_response(nil)
            (kafka_ex) lib/kafka_ex/server.ex:324: KafkaEx.Server.fetch/8
            (kafka_ex) lib/kafka_ex/server.ex:92: KafkaEx.Server.handle_call/3
            (stdlib) gen_server.erl:629: :gen_server.try_handle_call/4
            (stdlib) gen_server.erl:661: :gen_server.handle_msg/5
            (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
    (elixir) lib/gen_server.ex:564: GenServer.call/3
    (credit) lib/script.ex:12: Credit.fetch_loop/3
    (elixir) lib/code.ex:363: Code.require_file/2
    (mix) lib/mix/tasks/run.ex:68: Mix.Tasks.Run.run/1
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
```

Even when I restart my script I'm running in this error eventually. Only when I start the node again the script runs reliable.

Shouldn't the fetch message just return a Protocoll.Message with a specific error code (if at all) and not raise an exception?

**Comment by bjhaid** [comment] 2016-06-09 17:25
>>> Shouldn't the fetch message just return a Protocoll.Message with a specific error code (if at all) and not raise an exception?

Maybe? but maybe it's better to crash :) since that's the erlang way. So the problem is as thus:

Before every action we make to kafka (in this case `fetch`) we ask for the state of the cluster and rebalance the brokers we are aware of if things has changed, but there is a possibility of a race condition in between when we inquire the state of kafka and when we make the API request, which is exactly what happens here.

My suggested solution is thus:

- Monitor the process that runs the `fetch_loop` maybe via a `Supervisor` and restart it correctly when it crashes.
- Use [`Kafka.stream`](https://github.com/kafkaex/kafka_ex#stream-kafka-logs) instead of your `fetch_loop`
- if you run a version of kafka >= 0.8.2 you don't need to supplied offsets as that is managed by kafka consumer_groups

**Comment by dantswain** [comment] 2016-06-09 17:35
One thing I would add is that if you have multiple processes under a supervision tree and they're all using KafkaEx, you might need to tweak the supervisor's restart parameters.  I.e., if the max restarts is 3 and you have 3 processes that are linked to a single KafkaEx connection, once that connection crashes all 3 workers will restart and you could reach your supervisor's restart limit which would potentially crash your application.

**Comment by eproxus** [comment] 2016-06-20 09:49
@bjhaid I agree it's better to crash, but we've seen the same error and getting an `function_clause` error is not so nice. The immediate reaction is that this is a bug in the KafkaEx library:

```
    exception exit: {function_clause,
                        [{'Elixir.KafkaEx.Protocol.Fetch',parse_response,
                             [nil],
                             [{file,"lib/kafka_ex/protocol/fetch.ex"},
                              {line,18}]},
```

I think the `KafkaEx.NetworkClient` should raise an exception instead of returning `nil`. It already does detect and log the error so this wouldn't be any extra overhead.

**Comment by eproxus** [comment] 2016-06-20 11:45
If you're interested, I'd be happy to work on a pull request for better errors from the network level. It is something I'm interested in since we want to have higher uptime regardless of Kafka status. (Another case we found was shutting down Kafka and getting an `** (MatchError) no match of right hand side value: {:error, :einval}`).

**Comment by bjhaid** [comment] 2016-06-20 12:40
@eproxus Please send in the pull requests, I appreciate them ❤️

**Comment by bjhaid** [comment] 2016-06-24 15:19
I am closing this issue as I assume the concerns has been addressed with https://github.com/kafkaex/kafka_ex/pull/127#issuecomment-227465636, if you feel otherwise please reopen

**Closed by bjhaid** 2016-06-24 15:19 UTC
