### ISSUE TITLE
New to kafka_ex

### ISSUE THREAD

**Issue by jamsavvy** [kafkaex/kafka_ex#150] opened 2016-11-02 02:54 UTC
Hi, I'm new to Elixir and kafka_ex. I'm trying to run the sample producer.ex and other samples at http://www.abeji.de/kafka-meets-elixir/. 

However I'm encountering this error:

![producer_error](https://cloud.githubusercontent.com/assets/23204231/19915055/98f6dbb2-a0ea-11e6-9078-6af47e850d14.PNG)

Would appreciate any advice/help.

**Comment by bjhaid** [comment] 2016-11-02 03:10
that blogpost is over a year old, I am surprised the code there is still sort of relevant, you should try following the readme, here https://github.com/kafkaex/kafka_ex#produce-kafka-logs for producing kafka messages and let me know if you still have problems also make sure you are using kafka_ex 0.6.0 in your mix.exs file, I will also try to update that blog post such that it's more relevant

**Comment by bjhaid** [comment] 2016-11-02 03:30
hey, I can confirm using `0.6.0` version I can produce with the same code

and config.exs is:

```elixir
use Mix.Config
config :kafka_ex,
  brokers: [
    {"localhost", 9092},
    {"localhost", 9093},
    {"localhost", 9094},
  ],
  consumer_group: "kafka_ex",
```

instead of:

```elixir
use Mix.Config

config KafkaEx,
  brokers: [{"192.168.59.103", 49154}]
```

Fetch needs to be modified to:

`IO.inspect KafkaEx.fetch("kafka", 0, offset: 0)`

from:

`IO.inspect KafkaEx.fetch("kafka", 0, 0)`

every other thing on the blog is still valid :), I will update it soonish since people still find it useful

**Comment by jamsavvy** [comment] 2016-11-02 03:40
@bjhaid  Thank you very much, I'll try this and get back to you!

**Comment by jamsavvy** [comment] 2016-11-02 03:48
@bjhaid I tried running the producer.exs and so far so good, thanks again. Your blog is very helpful.

**Comment by bjhaid** [comment] 2016-11-02 12:14
I am closing this issue since it seems your problems have been resolved, I will update the blog as soon as I can

**Closed by bjhaid** 2016-11-02 12:14 UTC
