### ISSUE TITLE
Exception raised when producing

### ISSUE THREAD

**Issue by fbjork** [kafkaex/kafka_ex#26] opened 2015-06-26 23:04 UTC
Hi,

I'm using kafka_ex 0.0.2 in a Phoenix app and I get an exception when I try to produce a message:

Here's the output:

```
iex(1)> KafkaEx.create_worker(:feeds)
{:ok, #PID<0.299.0>}

iex(3)> KafkaEx.produce("feeds", 0, "hello")
** (exit) exited in: GenServer.call(KafkaEx.Server, {:produce, "feeds", 0, "hello", nil, 0, 100}, 5000)
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in :gen_tcp.send/2
            (kernel) gen_tcp.erl:261: :gen_tcp.send(nil, <<0, 0, 0, 0, 0, 0, 0, 1, 0, 8, 107, 97, 102, 107, 97, 95, 101, 120, 0, 0, 0, 0, 0, 100, 0, 0, 0, 1, 0, 5, 102, 101, 101, 100, 115, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 31, 0, 0, 0, ...>>)
            (kafka_ex) lib/kafka_ex/server.ex:126: KafkaEx.Server.send_data/2
            (kafka_ex) lib/kafka_ex/server.ex:21: KafkaEx.Server.handle_call/3
            (stdlib) gen_server.erl:607: :gen_server.try_handle_call/4
            (stdlib) gen_server.erl:639: :gen_server.handle_msg/5
            (stdlib) proc_lib.erl:237: :proc_lib.init_p_do_apply/3
    (elixir) lib/gen_server.ex:356: GenServer.call/3
[error] GenServer KafkaEx.Server terminating
Last message: {:produce, "feeds", 0, "hello", nil, 0, 100}
State: {1, %{brokers: %{0 => {"10.1.4.131", 9092}}, topics: %{"feeds" => %{error_code: 0, partitions: %{0 => %{error_code: 0, isrs: [0], leader: 0, replicas: [0]}}}}}, %{{"localhost", 9092} => #Port<0.5877>}, nil}
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in :gen_tcp.send/2
        (kernel) gen_tcp.erl:261: :gen_tcp.send(nil, <<0, 0, 0, 0, 0, 0, 0, 1, 0, 8, 107, 97, 102, 107, 97, 95, 101, 120, 0, 0, 0, 0, 0, 100, 0, 0, 0, 1, 0, 5, 102, 101, 101, 100, 115, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 31, 0, 0, 0, ...>>)
        (kafka_ex) lib/kafka_ex/server.ex:126: KafkaEx.Server.send_data/2
        (kafka_ex) lib/kafka_ex/server.ex:21: KafkaEx.Server.handle_call/3
        (stdlib) gen_server.erl:607: :gen_server.try_handle_call/4
        (stdlib) gen_server.erl:639: :gen_server.handle_msg/5
        (stdlib) proc_lib.erl:237: :proc_lib.init_p_do_apply/3
```

Any idea what's wrong?

**Comment by jacklund** [comment] 2015-06-28 23:52
What version are you using? Is it the latest?

Here's what I get when I run your example:

```
% iex -S mix
Erlang/OTP 17 [erts-6.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Interactive Elixir (1.0.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> KafkaEx.create_worker(:feeds)
{:ok, #PID<0.114.0>}
iex(2)> KafkaEx.produce("feeds", 0, "hello")
:ok
iex(3)>
```

Do you have your `config/config.exs` pointing to the published IP address of your Kafka server?

**Comment by fbjork** [comment] 2015-06-29 19:10
@jacklund this is the latest version (0.0.2).

Also, my kafka version is 0.8.2.1

Any ideas?

**Comment by fbjork** [comment] 2015-06-29 19:28
Also worth noting that this is a Phoenix app, not sure if it matters.

**Comment by gaynetdinov** [comment] 2015-07-03 12:21
The same here.

**Comment by jacklund** [comment] 2015-07-06 12:25
Verified in 0.0.2. I'll work on getting a working version (possibly the latest one) released as 0.0.3 today.

**Comment by jacklund** [comment] 2015-07-08 01:46
I've released version 0.1.0. That should fix this issue (not to mention add a good bit of functionality).

Let me know if there are still issues.

**Comment by bjhaid** [comment] 2015-07-16 02:56
@fbjork @gaynetdinov bump, does 0.1.0 fix your issues, so we can close this

**Comment by gaynetdinov** [comment] 2015-07-16 13:08
So I changed version of the `kafka_ex` from `0.0.2` to `0.1.0` in the `mix.exs` file, then I ran `mix deps.get` and `mix phoenix.server` and after that I got the following error:
```
=INFO REPORT==== 16-Jul-2015::15:05:51 ===
    application: logger
    exited: stopped
    type: temporary
** (Mix) Could not start application kafka_ex: KafkaEx.start(:normal, []) returned an error: an exception was raised:
    ** (Protocol.UndefinedError) protocol Enumerable not implemented for nil
        (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
        (elixir) lib/enum.ex:112: Enumerable.reduce/3
        (elixir) lib/enum.ex:981: Enum.map/2
        (kafka_ex) lib/kafka_ex/server.ex:19: KafkaEx.Server.init/1
        (stdlib) gen_server.erl:306: :gen_server.init_it/6
        (stdlib) proc_lib.erl:237: :proc_lib.init_p_do_apply/3
```

I even didn't change ip address of the kafka server from `10.90.29.80` to `localhost` in the `config.exs` file.

**Comment by bjhaid** [comment] 2015-07-16 13:30
@gaynetdinov your `config.exs` should contain something like:

```elixir
config :kafka_ex, # notice this part changed in 0.1.0
  brokers: [{HOST, PORT}]
```

I would update the README to reflect the correct thing

**Comment by gaynetdinov** [comment] 2015-07-16 13:40
@bjhaid ah sorry, I missed that. Now it works, thanks! But I got another problem: once I send one message to kafka, after 10-20 seconds I can see the following error in the log:

```
[error] GenServer KafkaEx.Server terminating
Last message: :update_consumer_metadata
State: %KafkaEx.Server{brokers: [%KafkaEx.Protocol.Metadata.Broker{host: "10.90.29.80", node_id: 0, port: 9092, socket: #Port<0.7092>}], consumer_group: "kafka_ex", consumer_metadata: %KafkaEx.Protocol.ConsumerMetadata.Response{coordinator_host: "", coordinator_id: 0, coordinator_port: 0, error_code: 0}, correlation_id: 5, event_pid: nil, metadata: %KafkaEx.Protocol.Metadata.Response{brokers: [%KafkaEx.Protocol.Metadata.Broker{host: "10.90.29.80", node_id: 0, port: 9092, socket: nil}], topic_metadatas: [%KafkaEx.Protocol.Metadata.TopicMetadata{error_code: 0, partition_metadatas: [%KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: 0, isrs: [0], leader: 0, partition_id: 0, replicas: [0]}], topic: "_schemas"}, %KafkaEx.Protocol.Metadata.TopicMetadata{error_code: 0, partition_metadatas: [%KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: 0, isrs: [0], leader: 0, partition_id: 0, replicas: [0]}], topic: "app_start"}]}}
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in KafkaEx.Protocol.ConsumerMetadata.parse_response/1
        (kafka_ex) lib/kafka_ex/protocol/consumer_metadata.ex:17: KafkaEx.Protocol.ConsumerMetadata.parse_response(nil)
        (kafka_ex) lib/kafka_ex/server.ex:175: KafkaEx.Server.update_consumer_metadata/3
        (kafka_ex) lib/kafka_ex/server.ex:154: KafkaEx.Server.handle_info/2
        (stdlib) gen_server.erl:593: :gen_server.try_dispatch/4
        (stdlib) gen_server.erl:659: :gen_server.handle_msg/5
        (stdlib) proc_lib.erl:237: :proc_lib.init_p_do_apply/3

```

This error message is repeated every ~15 seconds and kafka itself also writes the following error also every 10-15 seconds:

```
15:37:24 kafka.1           | [2015-07-16 15:37:24,278] ERROR Closing socket for /10.90.29.80 because of error (kafka.network.Processor)
15:37:24 kafka.1           | kafka.common.KafkaException: Wrong request type 10
15:37:24 kafka.1           |    at kafka.api.RequestKeys$.deserializerForKey(RequestKeys.scala:53)
15:37:24 kafka.1           |    at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:49)
15:37:24 kafka.1           |    at kafka.network.Processor.read(SocketServer.scala:353)
15:37:24 kafka.1           |    at kafka.network.Processor.run(SocketServer.scala:245)
15:37:24 kafka.1           |    at java.lang.Thread.run(Thread.java:745)
```

**Comment by bjhaid** [comment] 2015-07-16 13:51
@gaynetdinov what version of kafka are you running, the problem is the worker does not get to create a consumer_group on start, and we are assuming that there is always a coordinator when we try to refresh our internal state, it is a supervised process, so it should get restarted correctly, and probably might not affect you except with it logging restarts, once you get back with your kafka version I would look into fixing it later today, and we would probably get a fix out before weekend, thanks for catching this.

**Comment by gaynetdinov** [comment] 2015-07-16 13:57
@bjhaid because of the reasons I have to use a bit outdated version of kafka, I'm using 0.8.0 release: `kafka_2.8.0-0.8.0` version. Thank you the quick reply!

**Comment by bjhaid** [comment] 2015-07-16 14:05
@gaynetdinov ah that's why, the feature is supported in kafka 0.8.2, we would fix this so we don't break usability for older versions of kafka.

**Comment by gaynetdinov** [comment] 2015-07-16 14:06
Cool! :+1:

**Comment by bjhaid** [comment] 2015-09-21 23:04
closed with https://github.com/kafkaex/kafka_ex/releases/tag/0.2.0 published https://hex.pm/packages/kafka_ex/0.2.0

**Closed by bjhaid** 2015-09-21 23:04 UTC
