### ISSUE TITLE
If their is an error message set shouldn't be parsed

### ISSUE THREAD

**Issue by steffenix** [kafkaex/kafka_ex#197] opened 2017-03-14 03:57 UTC
I am getting the error:
```
(kafka_ex) lib/kafka_ex/protocol/fetch.ex:60: KafkaEx.Protocol.Fetch.parse_message_set([], <<0, 0, 0, 0, 0, 2, 108, 149, 0, 0, 0, 205, 151, 255, 119, 12, 0, 0, 255, 255, 255, 255, 0, 0, 0, 191, 138, 161, 97, 0, 161, 112, 204, 183, 161, 115, 204, 183, 161, 117, 218, 0, 36, 57, 98, 56, 57, 56, 101, 48, ...>>)
```
I wonder if the error code should be checked before trying to parse the message set?
[here](https://github.com/kafkaex/kafka_ex/blob/e240882d81095ee2ec2eb0a21e6391b8328185f0/lib/kafka_ex/protocol/fetch.ex#L57)

**Comment by dantswain** [comment] 2017-03-14 12:29
Thanks, @steffenix.  Could you please give us a little more of your stack trace?  What was the error code?

This gets tricky because this is an unexpected state and the general Elixir mantra of "fail fast" applies.  Kafka is telling us that the request could not be fulfilled.  Having said that, the error could definitely be a little more informative.

**Comment by steffenix** [comment] 2017-03-14 12:58
I am using kafka 0.8.2, I have the correct config to use the correct server.
I am using the default kafka worker.

**Comment by dcuddeback** [comment] 2017-03-14 19:21
The binary looks like the beginning of a valid message set. (offset=158,869, message size=205 bytes, crc=0x97ff770c, magic byte=0, attributes=0, key=null, value length=191) The two sizes (205 and 191) are consistent with each other (they're separated by 14 bytes). Without being able to see the full payload, my guess is that we're running into this:

> As an optimization the server is allowed to return a partial message at the end of the message set. Clients should handle this case.

https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-FetchAPI

The pattern matching in this function clause requires the full message to be present: https://github.com/kafkaex/kafka_ex/blob/e240882d81095ee2ec2eb0a21e6391b8328185f0/lib/kafka_ex/protocol/fetch.ex#L63.

**Comment by dantswain** [comment] 2017-03-14 19:34
@dcuddeback That is a good point, but without more of the stack trace we can't know if this was the error or not.  @steffenix mentions the error code but doesn't tell us which error code was received or if there even was one.  We really need more information here.

@dcuddeback Do you have any experience with the "partial message" being returned?  The wording in the documentation is very vague.  What is the client intended to do if a partial message is returned?  There's no API request corresponding to "send me the remainder of this partial message", at least not that I can tell :/

**Comment by dcuddeback** [comment] 2017-03-14 21:23
> Do you have any experience with the "partial message" being returned?

@dantswain I do not. Since it says it's an optimization, I hope it can just be ignored as if it wasn't intended to be part of the payload. Since the response does contain the size of the message, the client could presumably use that information to adjust the size of its next fetch request and attempt to refetch the message.

**Comment by bjhaid** [comment] 2017-03-14 21:37
for this particular case we should ignore the message, we already possibly throw away excess binary [here](https://github.com/kafkaex/kafka_ex/blob/master/lib/kafka_ex/protocol/metadata.ex#L110), and for fetch if the offset is not committed a subsequent fetch should be fine.

**Comment by dcuddeback** [comment] 2017-03-14 21:39
The Ruby client seems to ignore it, too: https://github.com/zendesk/ruby-kafka/commit/c933344cbd829c6d096d93a1dbd12f035b843081

**Comment by steffenix** [comment] 2017-03-15 01:29
@dantswain I couldn't get a dump of the full message as it crashed on the pattern matching. My guess was that they were an error making the pattern matching to fail but it might be partial message.

**Comment by ook** [comment] 2017-03-21 06:59
Sorry to enter that ticket that way, but it seriously looks like my current problem: I have streaming consumers (on your current `stream` branch) that are "stuck" on a given message, without payload returned by `KafkaEx.stream/3`, so the function return immediatly. When I have a look to the partition with `KafkaEx.earliest_offset/3` and `KafkaEx.latest_offset/3`, I see the partition is still growing. I'll try to solve by "ignoring" that offset if nothing happen and the partition still have other messages in partition.

**Comment by steffenix** [comment] 2017-03-21 07:22
In my case it was making the pattern matching crash.
Do you have any dump of your messages if you have the offset you can read the message from kafka. That would be nice to help on this issue.

**Comment by ook** [comment] 2017-03-21 09:07
Very interesting! Even now I think the problem is not related to that issue.
What I see when calling `KafkaEx.fetch/3` is the `message_set` contains only one message.
But when I call `KafkaEx.stream/3 |> Enum.take(1)` I get an empty collection:

```

**Comment by bjhaid** [comment] 2017-03-21 12:23
@ook you should not hijack a different issue/thread you should create a new issue instead, the offset in the fetch response struct is same as the offset you supplied as the last_offset, stream will intentionally not return this see [here](https://github.com/kafkaex/kafka_ex/blob/1a76e29687101660ba9a768b453f80009898b5f2/lib/kafka_ex/stream.ex#L25-L26) otherwise you will always get a message from the stream even when it should be empty like your current scenario

**Comment by Overbryd** [comment] 2018-01-11 13:07
This problem is currently halting our consumers. How to handle this?

**Closed** 2020-01-13 10:44 UTC
